name: Discord Notification Test

on: push

jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "GitHub Actions からの通知です！"
