name: Calculate Score

on: push

jobs:
  calculate-score:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run all local screenshot tests (Roborazzi)
        run: ./gradlew recordRoborazziDebug

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Calculate MS-SSIM
        run: python calculate_msssim.py

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot_result
          path: app/build/outputs/roborazzi
