name: Test roborazzi

on: [pull_request]

jobs:
  test-capture-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # setup gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      # run roborazzi
      - name: Run all local screenshot tests (Roborazzi)
        run: ./gradlew recordRoborazziDebug
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot_result
          path: app/build/outputs/roborazzi
